CREATE TABLE IF NOT EXISTS `data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATETIME` datetime NOT NULL,
  `DEVICE_VER` int(11) NOT NULL,
  `DHT22_ERROR` tinyint(1) NOT NULL,
  `BMP085_ERROR` tinyint(1) NOT NULL,
  `DHT22_TEMP_VAL` float(4,2) NOT NULL,
  `DHT22_HUM_VAL` float(4,2) NOT NULL,
  `DHT22_ROSNY_BOD` float(4,2) NOT NULL,
  `BMP085_TEMP_VAL` float(4,2) NOT NULL,
  `BMP085_PRES_VAL` float(8,2) NOT NULL,
  `BMP085_REL_TLAK` float(8,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci AUTO_INCREMENT=1 ;


